spring.application.name=pos-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/francos_pos
spring.datasource.username=postgres
spring.datasource.password=AQWfan30.
spring.jpa.hibernate.ddl-auto=update